<?php 
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/bootstrap-multiselect.js');
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/prettify.js');
$this->headScript()->appendFile($this->baseUrl().'/js/admin/user/edit.js');

$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/bootstrap-multiselect.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/prettify.css');

$employee = $this->user;
?>
<div class="container center">
    <div class="header">Editar: <?php echo $employee->getName();?></div>
            <form action="../User/updateUser" id="form" name="form" method="post" class="form-group">
                <input type="hidden" id="id" name="id" value="<?php echo $employee->getId();?>">
                <?php //if(isset($errorEmail)):?>
                  <!--   <label style="text-align: center; color: red;">Ya existe un usuario con el correo: <?php //echo $_GET["email"];?></label> -->
                <?php //endif;?>
                <?php //if(isset($errorEmail)):?>
                   <!--  <label style="text-align: center; color: red;">Ya existe un usuario con el nombre de usuario: <?php // echo $_GET["username"];?></label>  -->
                <?php // endif;?>

                <label ><span>Nombre de usuario:</span></label><input type="text" id="username" name="username"  value="<?php echo $employee->getUsername();?>"/>

                <label ><span>Contrase&ntilde;a: </span></label><input type="password" id="password" name="password" value="<?php //echo $employee->getPassword();?>"/>
                
                <label ><span>Nombre: </span></label><input type="text" id="name" name="name" value="<?php echo $employee->getName();?>"/>

                <label ><span>Apellido(s): </span></label><input type="text" id="lastName" name="lastName" value="<?php echo $employee->getLastName();?>"/>
                
                <label ><span>Correo: </span></label><input type="text" id="email" name="email" value="<?php echo $employee->getEmail();?>"/>
                
                <label ><span>Tipo: </span></label>
					<select id="typeUserId" name="typeUserId">
                    <option value="">Seleccione un tipo</option>
                    <?php 
                    foreach ($types as $type):?>
                    <?php if($type->getId() == $employee->getTypeUser()->getId()):?>
                    <option value="<?php echo $type->getId();?>" selected="selected"><?php echo $type->getName();?></option>
                    <?php 
                    continue;
                    endif;?>
                    <option value="<?php echo $type->getId();?>"><?php echo $type->getName();?></option>
					<?php endforeach;?>                    
                    </select>
                    <br>
                <input type="submit" name="editBtn" id="editBtn" value="Actualizar" class="right verde">
                <a id="btn_cancelar" value="Cancelar" href="../User/listUser" class="button left azul"><span class="icon fa-times"></span>Cancelar</a>
                <br>
                <br>
                <br>
            </form>
    
</div>