<?php 
$this->headScript()->appendFile($this->baseUrl().'/js/admin/user/edit.js');

$employee = $this->user;
?>
<div class="container center">
    <div class="header">Editar: <?php echo $employee->getName();?></div>
            <form action="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'update'),null,true);?>" id="form" name="form" method="post" class="form-group">
                <input type="hidden" id="id" name="id" value="<?php echo $employee->getId();?>">

                <label ><span>Nombre de usuario:</span></label><input type="text" id="username" name="username"  value="<?php echo $employee->getUsername();?>"/>
                <div id="errorName" class="col-md-3" style="display: none;">
                    <label style="text-align: center; color: red;"> El nombre de usuario ya existe</label>
                </div>
                
                <label ><span>Contrase&ntilde;a: </span></label><input type="password" id="password" name="password" value="<?php //echo $employee->getPassword();?>"/>
                
                <label ><span>Nombre: </span></label><input type="text" id="name" name="name" value="<?php echo $employee->getName();?>"/>

                <label ><span>Apellido(s): </span></label><input type="text" id="lastName" name="lastName" value="<?php echo $employee->getLastName();?>"/>
                
                <label ><span>Correo: </span></label><input type="text" id="email" name="email" value="<?php echo $employee->getEmail();?>"/>
                
                <label ><span>Tipo: </span></label>
					<select id="typeUserId" name="typeUserId">
                    <option value="">Seleccione un tipo</option>
                    <?php 
                    foreach ($this->typeUsers as $type):?>
                    <?php if($type->getId() == $employee->getTypeUser()->getId()):?>
                    <option value="<?php echo $type->getId();?>" selected="selected"><?php echo $type->getName();?></option>
                    <?php 
                    continue;
                    endif;?>
                    <option value="<?php echo $type->getId();?>"><?php echo $type->getName();?></option>
					<?php endforeach;?>                    
                    </select>
                    <br>
                <input type="submit" name="editBtn" id="editBtn" value="Actualizar" class="right verde">
                <a id="btn_cancelar" value="Cancelar" href="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'index'),null,true);?>" class="button left azul"><span class="icon fa-times"></span>Cancelar</a>
                <input type="hidden" id="urlEdit" value="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'evaluate-edit'),null,true);?>">
                <br>
                <br>
                <br>
            </form>
    
</div>