<?php

$this->headScript()->appendFile($this->baseUrl().'/js/admin/user/new.js');
//echo $this->headScript();
?>
<div class="container center">
	<div class="header">Nuevo Empleado</div>
        <div >
            <form action="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'new'),null,true);?>" id="form" name="form" method="post" class="form-group">
                 
                    <label ><span>Nombre de usuario:</span></label><input type="text" id="username" name="username"/>
                    <div id="errorName" class="col-md-3" style="display: none;">
                        <label style="text-align: center; color: red;"> El nombre de usuario ya existe</label>
                    </div>

                    <label ><span>Contrase&ntilde;a: </span></label><input type="password" id="password" name="password"/>
                
                    <label ><span>Nombre: </span></label><input type="text" id="name" name="name"/>

                    <label ><span>Apellido(s): </span></label><input type="text" id="lastName" name="lastName"/>
                
                    <label ><span>Correo: </span></label><input type="text" id="email" name="email"/>
                
                <label ><span>Tipo: </span>
					<select id="typeUserId" name="typeUserId">
                    <option value="">Seleccione un tipo</option>
                    <?php 
                    foreach ($this->typeUsers as $type):?>
                    <option value="<?php echo $type->getId();?>"><?php echo $type->getName();?></option>
				<?php endforeach;;?>                    
                    </select>
                    </label>
                <input type="submit" name="newBtn" id="newBtn" value="Agregar" class="right verde">
                <a id="btn_cancelar" value="Cancelar" href="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'index'),null,true);?>" class="button left azul"><span class="icon fa-times"></span>Cancelar</a>
                <input type="hidden" id="urlNew" value="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'evaluate-new'),null,true);?>">
                <br>
                <br>
                <br>
            </form>
        </div>
</div>

