<!DOCTYPE head PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <?php 

    $this->headLink()->appendStylesheet($this->baseUrl().'/css/main.css');

    echo $this->headLink();
  ?>
  <title>Videoclub</title>
</head>
<body>
    <div class="nav">
	<a href="<?php echo $this->url(array('module'=>'operator','controller' => 'client', 'action' => 'index'),null,true);?>" class="nav-button">Catalogo de clientes</a>
	<a href="<?php echo $this->url(array('module'=>'operator','controller' => 'cash-register', 'action' => 'index'),null,true);?>" class="nav-button">Corte de caja del d&iacute;a</a>
	<a href="<?php echo $this->url(array('module'=>'operator','controller' => 'rented-movies', 'action' => 'index'),null,true);?>" class="nav-button">Rentar pelicula</a>
	<a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout'),null,true);?>" class="exit-button right"><span class="icon fa-off"></span></a>
    </div>

      <?php echo $this->layout()->content?>


</body>
</html>