<?php 
$this->headScript()->appendFile($this->baseUrl().'/library/DataTables1.9/media/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->baseUrl().'/library/Datatables-Bootstrap3/BS3/assets/js/datatables.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/library/Datatables-Bootstrap3/BS3/assets/css/datatables.css');
?>
<div class="logo-container center">
	<img alt="" src="<?= $this->baseUrl()."/assets/logo_videoclub_estrella.jpg";?>">
</div>


   