<?php 
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/bootstrap-multiselect.js');
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/prettify.js');

$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/bootstrap-multiselect.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/prettify.css');

$this->headLink()->appendStylesheet($this->baseUrl().'/css/default/required.css');

$this->headScript()->appendFile($this->baseUrl().'/js/admin/movie/edit.js');

$movie = $this->movie;
?>

   <div class="container center">
   <div class="header">Editar Pelicula</div>

            <form action="../Movie/updateMovie" id="form" name="form" method="post" enctype="multipart/form-data" class="form-group">
                    <label ><span>Titulo: </span></label><input type="text" id="title" name="title" value="<?php echo $movie->getTitle();?>"/>
                    
                    <label ><span>Formato: </span></label><input type="text" id="format" name="format" value="<?php echo $movie->getFormat();?>"/>
                    
                    <label ><span>Total de unidades: </span></label><input type="number" id="totalUnits" min="1" name="totalUnits" value="<?php echo $movie->getTotalUnits();?>"/>
                    
                    <label ><span>A&ntilde;o: </span></label>
                    <select id="year" name="year">
                    <option value="">Seleccione un a&ntilde;o</option>
                    <?php for($i =1980; $i<2015; $i++):?>
                    <?php if($movie->getYear() == $i):?>
                    <option value="<?php echo $i;?>" selected="selected"><?php echo $i;?></option>
                    <?php 
                    continue;
                    endif;?>
                    <option value="<?php echo $i;?>"><?php echo $i;?></option>
					<?php endfor;?>                    
                    </select>
                    <input type="hidden" value="<?php echo $movie->getYear();?>"/>

                    <label ><span>Precio ($): </span></label><input type="number" min="1" id="price" name="price" value="<?php echo $movie->getPrice();?>"/>

                    <label ><span>C&oacute;digo: </span></label><input type="text" id="code" name="code" value="<?php echo $movie->getCode();?>"/>

                    <label ><span>G&eacute;nero: </span></label>
					<select id="genderId" name="genderId">
                    <option value="">Seleccione un g&eacute;nero</option>
                    <?php foreach ($this->genders as $gender):?>
                    <?php if($movie->getGender()->getId() == $gender->getId()):?>
                    <option value="<?php echo $gender->getId();?>" selected="selected"><?php echo $gender->getName();?></option>
                    <?php 
                    continue;
                    endif;?>
                    <option value="<?php echo $gender->getId();?>"><?php echo $gender->getName();?></option>
					<?php endforeach;;?>                    
                    </select>
                    <br>
                    <br>
                    <input type="hidden" id="id" name="id" value="<?php echo $movie->getId();?>">
                <input type="hidden" id="status" name="status" value="1">
                <input type="hidden" id="rentedUnits" name="rentedUnits" value="0">
                <input type="submit" name="newBtn" id="newBtn" value="Agregar" class="right verde">
                <a id="btn_cancelar" value="Cancelar" href="../Movie/listMovies" class="button left azul"><span class="icon fa-times"></span>Cancelar</a>
                <br>
                <br>
                <br>
            </form>
    </div>

</body>
</html>
   