<?php 
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/bootstrap-multiselect.js');
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/prettify.js');

$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/bootstrap-multiselect.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/prettify.css');

$this->headLink()->appendStylesheet($this->baseUrl().'/css/default/required.css');

$this->headScript()->appendFile($this->baseUrl().'/js/user/update.js');
//echo $this->headScript();
$typeUser = new Application_Model_TypeUser();
$arrayTypeUsers = $typeUser->getTypeUserArray();
$flag = false;
?>
    <div class="row">
        <div class="col-md-12">
            <h1>Editar Usuario</h1>
        </div>
    </div>
    
<div class="row">
    <div class="col-md-12">
        <form id="form" action="<?php echo $this->url(array('module'=>'admin', 'controller' => 'user', 'action' => 'update'));?>" method="post" class="form-horizontal" role="form">
            <div class="form-group">
                <label for="name" class="col-md-2 control-label"><label class="required">*</label>Nombre:</label>
                <div class="col-md-3">
                <input type="text" id="name" name="name"  class="form-control :required"  placeholder="Nombre" value="<?php echo $this->user->getName();?>"/>
                </div>
            </div>
            <div class="form-group">
                <label for="lastName" class="col-md-2 control-label"><label class="required">*</label>Apellido:</label>
                <div class="col-md-3">
                <input type="text" id="lastName" name="lastName" class="form-control :required"  placeholder="Apellido" value="<?php echo $this->user->getLastName();?>"/>
                </div>
            </div>
            <div class="form-group">
                <label for="username" class="col-md-2 control-label"><label class="required">*</label>Nombre de usuario:</label>
                <div class="col-md-3">
                <input type="text" id="username" name="username" class="form-control :required"  placeholder="Nombre de usuario" value="<?php echo $this->user->getUsername();?>"/>
                </div>
                <div id="errorName" class="col-md-3" style="display: none;">
                    <label class="required"> El nombre de usuario ya existe</label>
                </div>
            </div>
            <div class="form-group">
                    <label for="email" class="col-md-2 control-label"><label class="required">*</label>Email:</label>
                <div class="col-md-3">
                    <input type="text" id="email" name="email" class="form-control"  placeholder="Email" value="<?php echo $this->user->getEmail();?>"/>
                </div>
                 <div id="errorEmail" style="display: none;">
                    <label class="required"> El email ya ha sido registrado</label>
                </div>
            </div>
            <div class="form-group">
                <label for="id_typeUser" class="col-md-2 control-label"><label class="required">*</label>Tipo de usuario:</label>
                <div class="col-md-3">
                <select id="id_typeUser" name="id_typeUser" class=":required form-control" onchange="branchOnChange(this)">
                <?php foreach ($this->type as $type):?>
                    <?php if ($type->getId()!=$arrayTypeUsers["EMPLEADO"]):?>
                        <?php if ($type->getId()==$this->user->getTypeUsers()->getId()):?>
                            <option value="<?php echo $type->getId();?>" selected><?php echo $type->getName();?></option>
                        <?php else:?>
                            <option value="<?php echo $type->getId();?>"><?php echo $type->getName();?></option>
                        <?php endif;?>
                    <?php endif;?>
               <?php endforeach;?>
                </select>
                </div>
            </div>
            <div  id="branch" style="display: none;">
            <div class="form-group">
                <label for="id_branch" class="col-md-2 control-label"><label class="required">*</label>Sucursales:</label>
                <div class="col-md-3">
                <select id="id_branch" name="id_branch" class=":required form-control" multiple="multiple">
                    <?php foreach ($this->branch as $branch):?>
                        <?php if($this->user->getTypeUsers()->getId()==$arrayTypeUsers["SUPERVISOR"]):?>
                             <?php foreach ($this->branches as $branches):?>
                                 <?php if($branches->getId()==$branch->getId()):?>
                                 <?php $flag=true;?>
                                 <?php break;?>
                                 <?php endif;?>
                             <?php endforeach;?>
                             <?php if ($flag):?>
                                 <option value="<?php echo $branch->getId();?>" selected><?php echo $branch->getName();?></option> 
                                 <?php $flag=false;?>
                                 <?php else:?>
                                <option value="<?php echo $branch->getId();?>"><?php echo $branch->getName();?></option>
                                 <?php endif;?>
                        <?php else :?>
                             <option value="<?php echo $branch->getId();?>"><?php echo $branch->getName();?></option>
                        <?php endif;?>
                    <?php endforeach;?>
                </select>
                </div>
                
                <div id="errorBranch" class="col-md-3" style="display: none;">
                        <label class="required"> Seleccione al menos una sucursal</label>
                         </div>
            </div>
            </div>
             <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" id="changePass" name="changePass" onchange="optionPassword()"> Cambiar contraseña
                    </label>
                  </div>
                </div>
              </div>
             
             <div id="changePassword" style="display: none;">
                  <div class="form-group">
                    <label for="currentpassword" class="col-md-2 control-label"><label class="required">*</label>Contrase&ntilde;a Actual:</label>
                    <div class="col-md-3">
                    <input type="password" id="currentpassword" name="currentpassword" class="form-control :required"  placeholder="Contraseña actual"/>
                    </div>
                    <div id="errorPass" class="col-md-3" style="display: none;">
                    <label class="required">Contraseña incorrecta</label>
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="newpassword" class="col-md-2 control-label"><label class="required">*</label>Nueva Contrase&ntilde;a:</label>
                    <div class="col-md-3">
                    <input type="password" id="newpassword" name="newpassword" class="form-control :required"  placeholder="Nueva contraseña"/>
                    </div>
                  </div>
                   <div class="form-group">
                     <label for="confpassword" class="col-md-2 control-label"><label class="required">*</label>Confirmar nueva contrase&ntilde;a:</label>
                     <div class="col-md-3">
                     <input type="password" id="confpassword" name="confpassword" class="form-control :same_as;newpassword :required"  placeholder="Confirmar Contraseña"/>
                     </div>
                    </div>
             </div>
             
             <div class="form-group">
               <div class="col-md-offset-1 col-md-3">
                    <input class="btn btn-primary pull-right" type="submit" value="Actualizar"/>
                    <a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'user', 'action' => 'index'),null,true);?>" class="btn btn-default pull-right" style="margin-right: 10px;">Cancelar</a>
                </div>
            </div>
            
            <input type="hidden" id="id_user" name="id_user" value="<?php echo $this->user->getId();?>"/>
            <input type="hidden" id="password" name="password" value="<?php echo $this->user->getPassword();?>"/>
        </form>
    </div>
</div>