<?php 
    $this->headScript()->appendFile($this->baseUrl().'/js/admin/movie/index.js');
    
?>
<?php ?>
<div class="container center" >
	<input type="hidden" id="idRefresh" name="idRefresh" value="<?php echo (isset($_GET["refresh"]))? $_GET["refresh"]: "";?>"/>
	<div class="header">Peliculas</div>
        <div>
            <div class="actions">
	            <a href="<?php echo $this->url(array('module'=>'admin','controller' => 'movie', 'action' => 'new'),null,true);?>" class="button right verde"><span class="icon fa-plus"></span>Agregar Pelicula</a>
	            <a href="<?php echo $this->url(array('module'=>'admin','controller' => 'index', 'action' => 'index'),null,true);?>" class="button left azul"><span class="icon fa-home"></span>Regresar</a>
            </div>
            <table style="" border="1">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>T&iacute;tulo</th>
                        <th>Disponibles</th>
                        <th>Precio</th>
                        <th>G&eacute;nero</th>
                        <th>OPERACIONES</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->movies as $movie):?>
                        <tr>
                            <td><?php echo $movie->getId();?></td>
                            <td><?php echo utf8_encode($movie->getTitle());?></td>
                            <?php $available = ($movie->getTotalUnits()) - ($movie->getRentedUnits());?>
                            <td><?php echo $available;?></td>
                            <td><?php echo '$'.number_format($movie->getPrice(),2);?></td>
                            <td><?php echo utf8_encode($movie->getGender()->getName());?></td>
                            <td>
                                <a href="<?php echo $this->url(array('module'=>'admin','controller' => 'movie', 'action' => 'edit', 'id'=>$movie->getId()),null,true);?>" class="s-button verde"><span class="s-icon fa-edit"></span></a>
                                <a href="<?php echo $this->url(array('module'=>'admin','controller' => 'movie', 'action' => 'delete', 'id'=>$movie->getId()),null,true);?>" class="s-button rojo"><span class="s-icon fa-trash"></span></a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
    </div>
</div>

 