<?php
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/bootstrap-multiselect.js');
$this->headScript()->appendFile($this->baseUrl().'/library/bootstrap-multiselect/js/prettify.js');

$this->headScript()->appendFile($this->baseUrl().'/library/jqueryValidation/jquery-validation.js');

$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/bootstrap-multiselect.css');
$this->headLink()->appendStylesheet($this->baseUrl().'/library/bootstrap-multiselect/css/prettify.css');

$this->headLink()->appendStylesheet($this->baseUrl().'/css/default/required.css');

$this->headScript()->appendFile($this->baseUrl().'/js/user/new.js');
//echo $this->headScript();
$typeUser = new Application_Model_TypeUser();
$arrayTypeUsers = $typeUser->getTypeUserArray();
?>
<div class="row">
    <div class="col-md-12">
        <h1>Nuevo Usuario</h1>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <form action="<?php echo $this->url(array('module'=>'admin', 'controller' => 'user', 'action' => 'new'));?>" method="post" class="form-horizontal" role="form" id="form">
            <div class="form-group">
                  <label for="name" class="col-md-2 control-label"><label class="required">*</label>Nombre:</label>
                <div class="col-md-3">
                   <input type="text" id="name" name="name" class="form-control"  placeholder="Nombre"/>
                </div>
            </div>
            <div class="form-group">
                    <label for="lastName" class="col-md-2 control-label"><label class="required">*</label>Apellido:</label>
                <div class="col-md-3">
                    <input type="text" id="lastName" name="lastName" class="form-control"  placeholder="Apellido"/>
                </div>
            </div>
             <div class="form-group">
                <label for="username" class="col-md-2 control-label"><label class="required">*</label>Nombre de usuario:</label>
                <div class="col-md-3">
                <input type="text" id="username" name="username" class="form-control"  placeholder="Nombre de Usuario"/>
                </div>
                
                <div id="errorName" class="col-md-3" style="display: none;">
                    <label class="required"> El nombre de usuario ya existe</label>
                </div>
             </div>
             <div class="form-group">
                    <label for="email" class="col-md-2 control-label"><label class="required">*</label>Email:</label>
                <div class="col-md-3">
                    <input type="text" id="email" name="email" class="form-control"  placeholder="Email"/>
                </div>
                <div id="errorEmail" style="display: none;">
                    <label class="required"> El email ya ha sido registrado</label>
                </div>
            </div>
             <div class="form-group">
                <label for="password" class="col-md-2 control-label"><label class="required">*</label>Contrase&ntilde;a:</label>
                <div class="col-md-3">
                <input type="password" id="password" name="password" class="form-control"  placeholder="Contraseña"/>
                </div>
             </div>
             <div class="form-group">
                <label for="confpassword" class="col-md-2 control-label"><label class="required">*</label>Confirmar Contrase&ntilde;a:</label>
                <div class="col-md-3">
                <input type="password" id="confpassword" name="confpassword" class="form-control"  placeholder="Confirmar Contraseña"/>
                </div>
             </div>
             <div class="form-group">
                <label for="id_typeUser" class="col-md-2 control-label"><label class="required">*</label>Tipo de usuario:</label>
                <div class="col-md-3">
                    <select id="id_typeUser" name="id_typeUser" class="form-control" onChange="branchOnChange(this)">
                    <?php foreach ($this->types as $type):?> 
                        <?php if ($type->getId()!=$arrayTypeUsers["EMPLEADO"]):?>
                             <?php if ($type->getId()==$arrayTypeUsers["GERENTE"]):?>
                            <option value="<?php echo $type->getId(); ?>"  selected><?php echo $type->getName();?></option>
                            <?php else:?>
                             <option value="<?php echo $type->getId(); ?>"><?php echo $type->getName();?></option>
                            <?php endif;?>
                        <?php endif;?>
                    <?php endforeach;?>
                    </select>
                 </div>
               </div>
               <div  id="branch" style="display: none;">
                    <div class="form-group">
                        <label for="id_branch" class="col-md-2 control-label"><label class="required">*</label>Sucursales:</label>
                        <div class="col-md-3">
                            <select class="form-control" id="id_branch" name="id_branch" multiple="multiple">
                                <?php foreach ($this->branch as $branch):?> 
                                    <option value="<?php echo $branch->getId();?>"><?php echo $branch->getName();?></option>
                                <?php endforeach;?>
                            </select>
                        </div>
                        
                        <div id="errorBranch" class="col-md-3" style="display: none;">
                        <label class="required"> Seleccione al menos una sucursal</label>
                         </div>
                    </div>
               </div>
               
               <div class="form-group">
                    <div class="col-md-offset-1 col-md-3">
                        <input class="btn btn-primary pull-right" type="submit" value="Registrar"/>
                        <a href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'user', 'action' => 'index'));?>" class="btn btn-default pull-right" style="margin-right: 10px;">Cancelar</a>
                     </div>
                </div>
        </form>
    </div>
</div>