<!DOCTYPE head PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <?php
    $this->headScript()->prependFile($this->baseUrl() . '/library/jqueryValidation/jquery-validation.js');
    $this->headScript()->prependFile($this->baseUrl() . '/library/bootstrap.3.1.1/js/bootstrap.js');
    $this->headScript()->prependFile($this->baseUrl() . '/library/jquery/jquery-1.8.2.min.js');

    $this->headLink()->appendStylesheet($this->baseUrl() . '/css/main.css');
    $this->headLink()->appendStylesheet($this->baseUrl() . '/library/font-awesome-4.0.3/css/font-awesome.css');
    echo $this->headLink();
    echo $this->headScript();
    ?>
    <title>Videoclub</title>
</head>
<body>
<div class="nav">
	<a href="<?php echo $this->url(array('module'=>'admin','controller' => 'user', 'action' => 'index'),null,true);?>" class="nav-button">Catalogo de usuarios</a>
	<a href="<?php echo $this->url(array('module'=>'admin','controller' => 'movie', 'action' => 'index'),null,true);?>" class="nav-button">Catalogo de pel&iacute;culas</a>
	<a href="<?php echo $this->url(array('module'=>'admin','controller' => 'cash-register', 'action' => 'index'),null,true);?>" class="nav-button">Corte de caja del d&iacute;a</a>
	<a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'logout'),null,true);?>" class="exit-button right"><span class="icon fa-off"></span></a>
</div>
<br>
<br>

<div class="container">
    <div class="starter-template">
        <?php echo $this->layout()->content ?>
    </div>
</div>

</body>
</html>