<?php 
$serviceDate = new Application_Service_Date();
$total = 0;
?>
<div class="container center">
    <div class="header"><?php echo "Fecha de corte: ".$serviceDate->getDateFormat(Date('Y-m-d'));?></div>
    <div class="actions">
        <a href="<?php echo $this->url(array('module'=>'admin','controller' => 'index', 'action' => 'index'),null,true);?>" class="button left azul"><span class="icon fa-home"></span>Regresar</a>
    </div>
    <table>
        <thead>
        <tr>
            <th>Id</th>
            <th>Pelicula</th>
            <th>C&oacute;digo</th>
            <th>Precio Unitario</th>
            <th>Unidades rentadas</th>
            <th>Total</th>
        </tr>
        </thead>
        <tbody>
        <?php foreach($this->moviesRented as $movies):?>
            <?php $units = $movies["units"];?>
            <?php $movie = $movies["movie"];
            $totalMovie = $movie->getPrice()*$units;?>
            <tr>
                <td><?php echo $movie->getId();?></td>
                <td><?php echo $movie->getTitle();?></td>
                <td><?php echo $movie->getCode();?></td>
                <td><?php echo '$'.number_format($movie->getPrice(),"2");?></td>
                <td><?php echo $units;?></td>
                <td><?php echo '$'.number_format($totalMovie,"2");?></td>
            </tr>
            <?php $total += $totalMovie;?>
        <?php endforeach;?>
        </tbody>
    </table>

    <h3 class="right"><?php echo "Total: $".number_format($total,'2');?></h3>
    <br><br><br>
</div>
