<?php
$this->headScript()->appendFile($this->baseUrl() . '/js/employee/client/edit.js');
$client = $this->client;
?>

<div class="container center">
	<div class="header">Editar: <?php echo $client->name;?></div>
            <form id="form" action="<?php echo $this->url(array('module'=>'operator','controller' => 'client', 'action' => 'update',null,true));?>" id="form" name="form" method="post" class="form-group">
                <input type="hidden" id="id" name="id" value="<?php echo $client->getId();?>">
                    
                    <label ><span>Nombre: </span></label><input type="text" id="name" name="name" value="<?php echo $client->getName();?>"/>

                    <label ><span>Apellido(s): </span></label><input type="text" id="lastName" name="lastName" value="<?php echo $client->getLastName();?>"/>

                    <label ><span>Correo: </span></label><input type="text" id="email" name="email" value="<?php echo $client->getEmail();?>"/>

                    <label ><span>IFE: </span></label><input type="text" id="ife" name="ife" value="<?php echo $client->getIfe();?>"/>
                <br>
                <input type="submit" name="editBtn" id="editBtn" value="Actualizar" class="right verde">
                <a id="btn_cancelar" value="Cancelar" href="<?php echo $this->url(array('module'=>'operator','controller' => 'client', 'action' => 'index'),null,true);?>" class="button left azul"><span class="icon fa-times"></span>Cancelar</a>
            </form>
	<br><br><br>
</div>