<?php 
$this->headScript()->appendFile($this->baseUrl().'/library/DataTables1.9/media/js/jquery.dataTables.js');
$this->headScript()->appendFile($this->baseUrl().'/library/Datatables-Bootstrap3/BS3/assets/js/datatables.js');
$this->headLink()->appendStylesheet($this->baseUrl().'/library/Datatables-Bootstrap3/BS3/assets/css/datatables.css');
   // echo $this->headScript();
?>


<div class="container center" >
    <div class="header">Clientes</div>
            <div class="actions">
	            <a href="<?php echo $this->url(array('module'=>'operator','controller' => 'client', 'action' => 'new'),null,true);?>" class="button right verde"><span class="icon fa-plus"></span>Agregar cliente</a>
	            <a href="<?php echo $this->url(array('module'=>'operator','controller' => 'index', 'action' => 'index'),null,true);?>" class="button left azul"><span class="icon fa-home"></span>Regresar</a>
            </div>
            <table style="width:100%" border="1">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Correo</th>
                        <th>IFE</th>
                        <th>OPERACIONES</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->clients as $client):?>
                        <tr>
                            <td><?php echo $client->getId();?></td>
                            <td><?php echo utf8_encode($client->getName());?></td>
                            <td><?php echo $client->getLastName();?></td>
                            <td><?php echo $client->getEmail();?></td>
                            <td><?php echo $client->getIfe();?></td>
                            <td>
                                <a href="<?php echo $this->url(array('module'=>'operator','controller' => 'client', 'action' => 'edit', 'id'=>$client->getId()),null,true);?>"class="s-button verde"><span class="s-icon fa-edit"></span></a>
                                <a href="../Client/deleteClient?id=<?php echo $client->id;?>"class="s-button rojo"><span class="s-icon fa-trash"></span></a>
                            </td>
                        </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
    
</div>
